import * as ExcelJS from 'exceljs';
import {
  cellFormat,
  formatDate,
  formatDateTime,
  formatValue,
  prettifyStatus,
  statusTone,
  theme,
  toDate,
  toNumber,
} from './export-theme';
import {
  CellFormat,
  ExportColumn,
  ExportDocument,
  ExportSection,
  RenderedExport,
} from './export.types';

const argb = (hex: string) => `FF${hex}`;
const solid = (hex: string): ExcelJS.Fill => ({
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: argb(hex) },
});
const hairline: Partial<ExcelJS.Border> = { style: 'thin', color: { argb: argb(theme.border) } };
const FONT = 'Calibri';

const NUM_FMT: Partial<Record<CellFormat, string>> = {
  integer: '#,##0',
  number: '#,##0.00',
  currency: '"₦"#,##0.00;[Red]-"₦"#,##0.00',
  percent: '0.0%',
  date: 'dd mmm yyyy',
  datetime: 'dd mmm yyyy hh:mm',
};

const MAX_TABLE_ROW_SAMPLE = 300; // rows inspected when auto-sizing columns
const HEADER_ROW = 4; // data sheets: 1 title, 2 subtitle, 3 spacer, 4 header

export async function renderExcel(doc: ExportDocument): Promise<RenderedExport> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Kilo';
  workbook.company = 'Kilo';
  workbook.title = doc.title;
  workbook.created = new Date();

  const sheetNames = uniqueSheetNames(doc.sections);
  const summarySheet = workbook.addWorksheet('Summary', {
    properties: { tabColor: { argb: argb(theme.brand) } },
    views: [{ showGridLines: false }],
  });
  writeSummarySheet(summarySheet, doc, sheetNames);

  doc.sections.forEach((section, i) => {
    const sheet = workbook.addWorksheet(sheetNames[i], {
      properties: { tabColor: { argb: argb(theme.brandDark) } },
    });
    writeDataSheet(sheet, doc, section);
  });

  const raw = await workbook.xlsx.writeBuffer();
  return {
    buffer: Buffer.from(raw),
    contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    extension: 'xlsx',
  };
}

// ── Summary sheet ──────────────────────────────────────────────────────

function writeSummarySheet(sheet: ExcelJS.Worksheet, doc: ExportDocument, names: string[]) {
  sheet.columns = [{ width: 36 }, { width: 26 }, { width: 70 }];
  let row = 1;

  row = banner(sheet, row, 3, doc.title, doc.subtitle);
  row++;

  // Report details
  row = sectionBand(sheet, row, 3, 'REPORT DETAILS');
  const details: Array<[string, string]> = [
    ['Generated', formatDateTime(new Date())],
    ['Generated by', doc.generatedBy ?? 'Kilo Admin'],
  ];
  if (doc.period?.from || doc.period?.to) {
    details.push([
      'Period',
      `${doc.period.from ? formatDate(doc.period.from) : 'Beginning'} – ${
        doc.period.to ? formatDate(doc.period.to) : 'Now'
      }`,
    ]);
  }
  for (const [k, v] of Object.entries(doc.filters ?? {})) {
    details.push([`Filter: ${k}`, v]);
  }
  for (const s of doc.sections) {
    if (s.truncatedFrom) {
      details.push([
        'Note',
        `"${s.name}" lists the first ${s.rows.length.toLocaleString('en-US')} of ${s.truncatedFrom.toLocaleString('en-US')} matching records — narrow the filters to export the rest.`,
      ]);
    }
  }
  for (const [label, value] of details) {
    const r = sheet.getRow(row++);
    r.getCell(1).value = label;
    r.getCell(1).font = { name: FONT, bold: true, size: 11, color: { argb: argb(theme.muted) } };
    sheet.mergeCells(r.number, 2, r.number, 3);
    r.getCell(2).value = value;
    r.getCell(2).font = { name: FONT, size: 11, color: { argb: argb(theme.text) } };
    r.getCell(2).alignment = { horizontal: 'left', vertical: 'middle', wrapText: true };
    if (value.length > 90) r.height = 30;
  }
  row++;

  // Key metrics
  if (doc.summary.length > 0) {
    row = sectionBand(sheet, row, 3, 'KEY METRICS');
    row = tableHeader(sheet, row, ['Metric', 'Value', 'How it is calculated']);
    doc.summary.forEach((metric, i) => {
      const r = sheet.getRow(row++);
      r.height = metric.note && metric.note.length > 85 ? 32 : 22;
      const band = i % 2 === 1 ? theme.band : theme.white;

      const label = r.getCell(1);
      label.value = metric.label;
      label.font = { name: FONT, size: 11, bold: true, color: { argb: argb(theme.text) } };
      label.fill = solid(band);

      const value = r.getCell(2);
      writeTypedValue(value, metric.value, metric.format ?? 'text');
      const tone = theme.tone[metric.tone ?? 'neutral'];
      value.font = { name: FONT, size: 12, bold: true, color: { argb: argb(tone.fg) } };
      value.fill = solid(metric.tone ? tone.bg : band);
      value.alignment = { horizontal: 'right', vertical: 'middle' };

      const note = r.getCell(3);
      note.value = metric.note ?? '';
      note.font = { name: FONT, size: 10, italic: true, color: { argb: argb(theme.muted) } };
      note.fill = solid(band);
      note.alignment = { vertical: 'middle', wrapText: true };

      for (let c = 1; c <= 3; c++) {
        r.getCell(c).border = { bottom: hairline };
        if (c !== 2) r.getCell(c).alignment = { vertical: 'middle', wrapText: true };
      }
    });
    row++;
  }

  // Contents
  row = sectionBand(sheet, row, 3, 'CONTENTS');
  row = tableHeader(sheet, row, ['Sheet', 'Records', 'Description']);
  doc.sections.forEach((section, i) => {
    const r = sheet.getRow(row++);
    r.height = 22;
    const link = r.getCell(1);
    link.value = { text: names[i], hyperlink: `#'${names[i]}'!A1` };
    link.font = { name: FONT, size: 11, underline: true, color: { argb: argb(theme.brand) } };
    const count = r.getCell(2);
    count.value = section.rows.length;
    count.numFmt = '#,##0';
    count.alignment = { horizontal: 'right', vertical: 'middle' };
    count.font = { name: FONT, size: 11, color: { argb: argb(theme.text) } };
    const desc = r.getCell(3);
    desc.value = section.description ?? section.title ?? section.name;
    desc.font = { name: FONT, size: 10, color: { argb: argb(theme.muted) } };
    desc.alignment = { vertical: 'middle', wrapText: true };
    for (let c = 1; c <= 3; c++) r.getCell(c).border = { bottom: hairline };
  });

  sheet.pageSetup = {
    orientation: 'portrait',
    paperSize: 9,
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
  };
  sheet.headerFooter.oddFooter = `&L&8Kilo — ${escapeFooter(doc.title)}&R&8Page &P of &N`;
}

// ── Data sheet ─────────────────────────────────────────────────────────

function writeDataSheet(sheet: ExcelJS.Worksheet, doc: ExportDocument, section: ExportSection) {
  const cols = section.columns;
  const n = Math.max(cols.length, 1);
  const widths = cols.map((c) => columnWidth(c, section.rows));
  sheet.columns = widths.map((width) => ({ width }));

  banner(sheet, 1, n, section.title ?? section.name, undefined);
  const sub = sheet.getRow(2);
  sheet.mergeCells(2, 1, 2, n);
  const shown = section.rows.length.toLocaleString('en-US');
  sub.getCell(1).value = section.truncatedFrom
    ? `${doc.title} · first ${shown} of ${section.truncatedFrom.toLocaleString('en-US')} records`
    : `${doc.title} · ${shown} record${section.rows.length === 1 ? '' : 's'}`;
  sub.getCell(1).font = { name: FONT, size: 10, italic: true, color: { argb: argb(theme.muted) } };
  sub.getCell(1).alignment = { vertical: 'middle' };

  tableHeader(
    sheet,
    HEADER_ROW,
    cols.map((c) => c.header),
  );

  const first = HEADER_ROW + 1;
  section.rows.forEach((data, i) => {
    const r = sheet.getRow(first + i);
    const band = i % 2 === 1 ? theme.band : theme.white;
    cols.forEach((col, c) => {
      const cell = r.getCell(c + 1);
      const format = cellFormat(col, data);
      writeTypedValue(cell, data[col.key], format);
      cell.fill = solid(band);
      cell.border = { bottom: hairline };
      cell.font = { name: FONT, size: 10, color: { argb: argb(theme.text) } };
      cell.alignment = { vertical: 'middle', horizontal: alignFor(format) };
      if (format === 'status' && cell.value) {
        const tone = theme.tone[statusTone(data[col.key])];
        cell.fill = solid(tone.bg);
        cell.font = { name: FONT, size: 10, bold: true, color: { argb: argb(tone.fg) } };
      }
    });
  });

  const last = first + section.rows.length - 1;
  if (section.rows.length > 0 && cols.some((c) => c.total)) {
    const t = sheet.getRow(last + 1);
    t.height = 22;
    cols.forEach((col, c) => {
      const cell = t.getCell(c + 1);
      cell.fill = solid(theme.brandTint);
      cell.border = { top: { style: 'medium', color: { argb: argb(theme.brand) } } };
      cell.font = { name: FONT, size: 10, bold: true, color: { argb: argb(theme.brandDark) } };
      cell.alignment = { vertical: 'middle', horizontal: alignFor(col.format ?? 'text') };
      if (c === 0) cell.value = 'Total';
      if (col.total) {
        const letter = sheet.getColumn(c + 1).letter;
        const sum = section.rows.reduce((acc, row) => acc + (toNumber(row[col.key]) ?? 0), 0);
        // SUBTOTAL (109) so the total follows whatever the reader filters to;
        // `result` keeps the figure visible in viewers that don't recalculate.
        cell.value = { formula: `SUBTOTAL(109,${letter}${first}:${letter}${last})`, result: sum };
        cell.numFmt = NUM_FMT[col.format ?? 'number'] ?? '#,##0.00';
      }
    });
  }

  if (section.rows.length === 0) {
    const empty = sheet.getRow(first);
    sheet.mergeCells(first, 1, first, n);
    empty.getCell(1).value = 'No records match the selected filters.';
    empty.getCell(1).font = {
      name: FONT,
      size: 11,
      italic: true,
      color: { argb: argb(theme.muted) },
    };
    empty.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
    empty.height = 32;
  }

  sheet.views = [{ state: 'frozen', ySplit: HEADER_ROW, showGridLines: false }];
  if (section.rows.length > 0) {
    sheet.autoFilter = {
      from: { row: HEADER_ROW, column: 1 },
      to: { row: HEADER_ROW, column: n },
    };
  }
  sheet.pageSetup = {
    orientation: cols.length > 6 ? 'landscape' : 'portrait',
    paperSize: 9,
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    printTitlesRow: `${HEADER_ROW}:${HEADER_ROW}`,
  };
  sheet.headerFooter.oddFooter = `&L&8Kilo — ${escapeFooter(doc.title)}&R&8Page &P of &N`;
}

// ── Building blocks ────────────────────────────────────────────────────

/** Full-width brand title band (+ optional subtitle row). Returns next free row. */
function banner(
  sheet: ExcelJS.Worksheet,
  rowNo: number,
  span: number,
  title: string,
  subtitle?: string,
): number {
  sheet.mergeCells(rowNo, 1, rowNo, span);
  const r = sheet.getRow(rowNo);
  r.height = 38;
  const cell = r.getCell(1);
  cell.value = title;
  cell.font = { name: FONT, size: 18, bold: true, color: { argb: argb(theme.white) } };
  cell.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 };
  for (let c = 1; c <= span; c++) r.getCell(c).fill = solid(theme.brand);

  let next = rowNo + 1;
  if (subtitle) {
    sheet.mergeCells(next, 1, next, span);
    const s = sheet.getRow(next);
    s.height = 22;
    s.getCell(1).value = subtitle;
    s.getCell(1).font = { name: FONT, size: 11, italic: true, color: { argb: argb(theme.muted) } };
    s.getCell(1).alignment = { vertical: 'middle', indent: 1 };
    next++;
  }
  return next;
}

function sectionBand(sheet: ExcelJS.Worksheet, rowNo: number, span: number, label: string) {
  sheet.mergeCells(rowNo, 1, rowNo, span);
  const r = sheet.getRow(rowNo);
  r.height = 22;
  const cell = r.getCell(1);
  cell.value = label;
  cell.font = { name: FONT, size: 10, bold: true, color: { argb: argb(theme.brandDark) } };
  cell.alignment = { vertical: 'middle', indent: 1 };
  for (let c = 1; c <= span; c++) {
    r.getCell(c).fill = solid(theme.brandTint);
    r.getCell(c).border = { bottom: { style: 'medium', color: { argb: argb(theme.brand) } } };
  }
  return rowNo + 1;
}

function tableHeader(sheet: ExcelJS.Worksheet, rowNo: number, headers: string[]) {
  const r = sheet.getRow(rowNo);
  r.height = 26;
  headers.forEach((h, i) => {
    const cell = r.getCell(i + 1);
    cell.value = h;
    cell.font = { name: FONT, size: 10, bold: true, color: { argb: argb(theme.white) } };
    cell.fill = solid(theme.brandDark);
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border = { right: { style: 'thin', color: { argb: argb(theme.brand) } } };
  });
  return rowNo + 1;
}

/** Writes a real typed cell (number/date), so Excel can sort, filter and sum it. */
function writeTypedValue(cell: ExcelJS.Cell, raw: unknown, format: CellFormat) {
  switch (format) {
    case 'integer':
    case 'number':
    case 'currency':
    case 'percent': {
      const n = toNumber(raw);
      if (n === null) {
        cell.value = raw === null || raw === undefined ? null : String(raw);
        break;
      }
      cell.value = n;
      cell.numFmt = NUM_FMT[format]!;
      break;
    }
    case 'date':
    case 'datetime': {
      const d = toDate(raw);
      cell.value = d;
      if (d) cell.numFmt = NUM_FMT[format]!;
      break;
    }
    case 'status':
      cell.value = raw === null || raw === undefined || raw === '' ? null : prettifyStatus(raw);
      break;
    default:
      cell.value = raw === null || raw === undefined ? null : String(raw);
  }
}

function alignFor(format: CellFormat): 'left' | 'right' | 'center' {
  switch (format) {
    case 'integer':
    case 'number':
    case 'currency':
    case 'percent':
      return 'right';
    case 'date':
    case 'datetime':
    case 'status':
      return 'center';
    default:
      return 'left';
  }
}

function columnWidth(col: ExportColumn, rows: Record<string, unknown>[]): number {
  if (col.width) return col.width;
  let longest = col.header.length;
  for (const row of rows.slice(0, MAX_TABLE_ROW_SAMPLE)) {
    longest = Math.max(longest, formatValue(row[col.key], col.format).length);
  }
  if (col.total) {
    // a sum is wider than any row it adds up — a too-narrow numeric cell shows "####"
    const sum = rows.reduce((acc, row) => acc + (toNumber(row[col.key]) ?? 0), 0);
    longest = Math.max(longest, formatValue(sum, col.format ?? 'number').length + 2);
  }
  return Math.min(48, Math.max(11, longest + 3));
}

// Excel sheet names: ≤31 chars, none of \ / ? * [ ] :, unique, not 'Summary'.
function uniqueSheetNames(sections: ExportSection[]): string[] {
  const taken = new Set<string>(['summary']);
  return sections.map((s) => {
    const base = (s.name.replace(/[\\/?*[\]:]/g, '-').trim() || 'Data').slice(0, 31);
    let name = base;
    let i = 2;
    while (taken.has(name.toLowerCase())) {
      const suffix = ` (${i++})`;
      name = base.slice(0, 31 - suffix.length) + suffix;
    }
    taken.add(name.toLowerCase());
    return name;
  });
}

// '&' starts a control code in Excel header/footer strings.
function escapeFooter(text: string): string {
  return text.replace(/&/g, '&&');
}
