import { PrismaService } from '../../prisma/prisma.service';
import { prettifyStatus } from './export-theme';

/** "Generated by" line for an export: the admin's name, else a safe fallback. */
export async function resolveActorName(
  prisma: PrismaService,
  actorId: string | undefined,
): Promise<string> {
  if (!actorId) return 'Kilo Admin';
  const user = await prisma.user.findUnique({
    where: { id: actorId },
    select: { firstName: true, lastName: true, email: true },
  });
  const name = `${user?.firstName ?? ''} ${user?.lastName ?? ''}`.trim();
  return name || user?.email || 'Kilo Admin';
}

/**
 * Human-readable list of the filters an export was run with. Unset values are
 * dropped; ENUM_STYLE values become "Enum style".
 */
export function describeFilters(
  filters: Record<string, string | number | undefined | null>,
): Record<string, string> | undefined {
  const out: Record<string, string> = {};
  for (const [label, value] of Object.entries(filters)) {
    if (value === undefined || value === null || String(value).trim() === '') continue;
    const text = String(value).trim();
    out[label] = /^[A-Z][A-Z_]+$/.test(text) ? prettifyStatus(text) : text;
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

/** Period header from optional ISO `from`/`to` query strings. */
export function periodOf(query: { from?: string; to?: string }) {
  if (!query.from && !query.to) return undefined;
  return {
    from: query.from ? new Date(query.from) : undefined,
    to: query.to ? new Date(query.to) : undefined,
  };
}

export function fullName(user: { firstName?: string | null; lastName?: string | null }): string {
  return `${user.firstName ?? ''} ${user.lastName ?? ''}`.trim();
}
