import PDFDocument from 'pdfkit';
import {
  cellFormat,
  formatDate,
  formatDateTime,
  formatValue,
  statusTone,
  theme,
  toNumber,
} from './export-theme';
import {
  CellFormat,
  ExportColumn,
  ExportDocument,
  ExportMetric,
  ExportSection,
  RenderedExport,
} from './export.types';

const MARGIN = 36;
const FOOTER_RESERVE = 26;
const ROW_H = 18;
const HEAD_H = 22;
const CELL_PAD = 6;
const FONT = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';
const FONT_ITALIC = 'Helvetica-Oblique';

const hex = (h: string) => `#${h}`;

// The built-in PDF fonts are WinAnsi (Latin-1 plus a few punctuation marks):
// no ₦, and no Yoruba sub-dot letters (ẹ ọ ṣ) that real names contain — they
// would print as broken glyphs. Decompose what we can (ẹ -> e), drop what we
// can't. Money is written "NGN 1,000.00" in PDFs for the same reason.
const WIN_ANSI_EXTRAS = new Set('€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ'.split(''));
export function pdfSafe(text: string): string {
  let out = '';
  for (const ch of text.normalize('NFC')) {
    const cp = ch.codePointAt(0)!;
    if (cp <= 0xff || WIN_ANSI_EXTRAS.has(ch)) {
      out += cp < 0x20 && cp !== 0x09 ? ' ' : ch;
      continue;
    }
    const base = ch.normalize('NFD').replace(/[̀-ͯ]/g, '');
    out += [...base].every((c) => c.codePointAt(0)! <= 0xff) ? base : '?';
  }
  return out;
}

export function renderPdf(document: ExportDocument): Promise<RenderedExport> {
  const widest = Math.max(0, ...document.sections.map((s) => s.columns.length));
  const landscape = widest > 5;

  const pdf = new PDFDocument({
    size: 'A4',
    layout: landscape ? 'landscape' : 'portrait',
    margin: MARGIN,
    bufferPages: true,
    info: { Title: document.title, Author: 'Kilo', Creator: 'Kilo Admin' },
  });
  const chunks: Buffer[] = [];
  const done = new Promise<RenderedExport>((resolve, reject) => {
    pdf.on('data', (c: Buffer) => chunks.push(c));
    pdf.on('error', reject);
    pdf.on('end', () =>
      resolve({ buffer: Buffer.concat(chunks), contentType: 'application/pdf', extension: 'pdf' }),
    );
  });

  new PdfLayout(pdf, document).render();
  pdf.end();
  return done;
}

class PdfLayout {
  private y = 0;
  private readonly width: number;
  private readonly bottom: number;

  constructor(
    private readonly pdf: PDFKit.PDFDocument,
    private readonly document: ExportDocument,
  ) {
    this.width = pdf.page.width - MARGIN * 2;
    this.bottom = pdf.page.height - MARGIN - FOOTER_RESERVE;
  }

  render() {
    this.drawHeader();
    this.drawMeta();
    this.drawSummary(this.document.summary);
    for (const section of this.document.sections) {
      this.drawSection(section);
    }
    this.drawFooters();
  }

  // ── Page furniture ──────────────────────────────────────────────────

  private drawHeader() {
    const { pdf, document } = this;
    const pageW = pdf.page.width;
    pdf.rect(0, 0, pageW, 74).fill(hex(theme.brand));
    pdf.rect(0, 74, pageW, 3).fill(hex(theme.brandDark));

    pdf.font(FONT_BOLD).fontSize(20).fillColor(hex(theme.white));
    this.text(document.title, MARGIN, 18, { width: this.width - 140 });
    if (document.subtitle) {
      pdf.font(FONT).fontSize(10).fillColor('#C7D2FE');
      this.text(document.subtitle, MARGIN, 46, { width: this.width - 140 });
    }
    pdf.font(FONT_BOLD).fontSize(16).fillColor(hex(theme.white));
    this.text('KILO', MARGIN, 18, { width: this.width, align: 'right' });
    pdf.font(FONT).fontSize(8).fillColor('#C7D2FE');
    this.text(formatDateTime(new Date()), MARGIN, 42, { width: this.width, align: 'right' });
    this.y = 92;
  }

  private drawMeta() {
    const { document } = this;
    const lines: string[] = [];
    if (document.period?.from || document.period?.to) {
      lines.push(
        `Period: ${document.period.from ? formatDate(document.period.from) : 'Beginning'} – ${
          document.period.to ? formatDate(document.period.to) : 'Now'
        }`,
      );
    }
    const filters = Object.entries(document.filters ?? {});
    if (filters.length > 0) {
      lines.push(`Filters: ${filters.map(([k, v]) => `${k}: ${v}`).join('  ·  ')}`);
    }
    lines.push(`Generated by: ${document.generatedBy ?? 'Kilo Admin'}`);

    this.pdf.font(FONT).fontSize(8.5).fillColor(hex(theme.muted));
    for (const line of lines) {
      this.text(line, MARGIN, this.y, { width: this.width });
      this.y += 13;
    }
    this.y += 8;
  }

  private drawFooters() {
    const { pdf, document } = this;
    const range = pdf.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      pdf.switchToPage(i);
      pdf.page.margins.bottom = 0; // footer sits inside the bottom margin
      const y = pdf.page.height - MARGIN - 6;
      pdf
        .moveTo(MARGIN, y - 6)
        .lineTo(MARGIN + this.width, y - 6)
        .lineWidth(0.5)
        .strokeColor(hex(theme.border))
        .stroke();
      pdf.font(FONT).fontSize(8).fillColor(hex(theme.muted));
      this.text(`Kilo · ${document.title}`, MARGIN, y, { width: this.width / 2 });
      this.text(`Page ${i - range.start + 1} of ${range.count}`, MARGIN, y, {
        width: this.width,
        align: 'right',
      });
    }
  }

  // ── Summary cards ───────────────────────────────────────────────────

  private drawSummary(metrics: ExportMetric[]) {
    if (metrics.length === 0) return;
    const gap = 10;
    const perRow = this.pdf.page.layout === 'landscape' ? 4 : 3;
    const cols = Math.min(perRow, metrics.length);
    const cardW = (this.width - gap * (cols - 1)) / cols;
    const cardH = 54;

    this.sectionHeading('Summary');
    metrics.forEach((metric, i) => {
      const col = i % cols;
      if (col === 0) {
        this.ensure(cardH + gap);
        if (i > 0) this.y += cardH + gap;
      }
      this.drawCard(metric, MARGIN + col * (cardW + gap), this.y, cardW, cardH);
    });
    this.y += cardH + 18;
  }

  private drawCard(metric: ExportMetric, x: number, y: number, w: number, h: number) {
    const { pdf } = this;
    const tone = theme.tone[metric.tone ?? 'neutral'];
    pdf.roundedRect(x, y, w, h, 5).fill(hex(metric.tone ? tone.bg : theme.band));
    pdf.roundedRect(x, y, w, h, 5).lineWidth(0.5).strokeColor(hex(theme.border)).stroke();
    pdf.rect(x, y + 6, 3.5, h - 12).fill(hex(tone.accent));

    pdf.font(FONT_BOLD).fontSize(7.5).fillColor(hex(theme.muted));
    this.text(metric.label.toUpperCase(), x + 12, y + 9, { width: w - 20, ellipsis: true });

    const value = formatValue(metric.value, metric.format) || '—';
    let size = 17;
    pdf.font(FONT_BOLD);
    while (size > 9 && pdf.fontSize(size).widthOfString(pdfSafe(value)) > w - 22) size -= 1;
    pdf.fillColor(hex(tone.fg));
    this.text(value, x + 12, y + 26, { width: w - 20, ellipsis: true });
  }

  // ── Tables ──────────────────────────────────────────────────────────

  private drawSection(section: ExportSection) {
    this.ensure(HEAD_H + ROW_H * 3 + 40);
    this.sectionHeading(section.title ?? section.name);
    if (section.description) {
      this.pdf.font(FONT_ITALIC).fontSize(8.5).fillColor(hex(theme.muted));
      this.text(section.description, MARGIN, this.y - 4, { width: this.width });
      this.y += 12;
    }
    if (section.truncatedFrom) {
      this.pdf.font(FONT_ITALIC).fontSize(8.5).fillColor(hex(theme.tone.warn.fg));
      this.text(
        `Showing the first ${section.rows.length.toLocaleString('en-US')} of ${section.truncatedFrom.toLocaleString('en-US')} matching records — narrow the filters to export the rest.`,
        MARGIN,
        this.y - 4,
        { width: this.width },
      );
      this.y += 12;
    }

    const widths = this.columnWidths(section);
    this.drawTableHeader(section.columns, widths);

    if (section.rows.length === 0) {
      this.pdf.font(FONT_ITALIC).fontSize(9).fillColor(hex(theme.muted));
      this.text('No records match the selected filters.', MARGIN, this.y + 8, {
        width: this.width,
        align: 'center',
      });
      this.y += 34;
      return;
    }

    section.rows.forEach((row, i) => {
      if (this.y + ROW_H > this.bottom) {
        this.pdf.addPage();
        this.y = MARGIN;
        this.drawTableHeader(section.columns, widths);
      }
      this.drawRow(section.columns, widths, row, i % 2 === 1);
    });

    if (section.columns.some((c) => c.total)) {
      if (this.y + ROW_H > this.bottom) {
        this.pdf.addPage();
        this.y = MARGIN;
      }
      this.drawTotals(section, widths);
    }
    this.y += 20;
  }

  private drawTableHeader(columns: ExportColumn[], widths: number[]) {
    const { pdf } = this;
    pdf.rect(MARGIN, this.y, this.width, HEAD_H).fill(hex(theme.brandDark));
    pdf.font(FONT_BOLD).fontSize(8).fillColor(hex(theme.white));
    let x = MARGIN;
    columns.forEach((col, i) => {
      this.cellText(col.header, x, this.y + 7, widths[i], alignOf(col.format));
      x += widths[i];
    });
    this.y += HEAD_H;
  }

  private drawRow(
    columns: ExportColumn[],
    widths: number[],
    row: Record<string, unknown>,
    banded: boolean,
  ) {
    const { pdf } = this;
    if (banded) pdf.rect(MARGIN, this.y, this.width, ROW_H).fill(hex(theme.band));
    pdf
      .moveTo(MARGIN, this.y + ROW_H)
      .lineTo(MARGIN + this.width, this.y + ROW_H)
      .lineWidth(0.4)
      .strokeColor(hex(theme.border))
      .stroke();

    let x = MARGIN;
    columns.forEach((col, i) => {
      const format = cellFormat(col, row);
      const text = formatValue(row[col.key], format);
      if (format === 'status' && text) {
        this.drawPill(text, statusTone(row[col.key]), x, this.y, widths[i]);
      } else {
        pdf.font(FONT).fontSize(8).fillColor(hex(theme.text));
        this.cellText(text, x, this.y + 5.5, widths[i], alignOf(format));
      }
      x += widths[i];
    });
    this.y += ROW_H;
  }

  private drawPill(
    text: string,
    toneName: ReturnType<typeof statusTone>,
    x: number,
    y: number,
    w: number,
  ) {
    const { pdf } = this;
    const tone = theme.tone[toneName];
    pdf.font(FONT_BOLD).fontSize(7);
    const safe = pdfSafe(text);
    const textW = Math.min(pdf.widthOfString(safe), w - CELL_PAD * 2 - 8);
    const pillW = textW + 12;
    const px = x + (w - pillW) / 2;
    pdf.roundedRect(px, y + 3, pillW, ROW_H - 6, 4).fill(hex(tone.bg));
    pdf.fillColor(hex(tone.fg));
    this.text(text, px + 6, y + 6.2, { width: textW + 1, ellipsis: true });
  }

  private drawTotals(section: ExportSection, widths: number[]) {
    const { pdf } = this;
    pdf.rect(MARGIN, this.y, this.width, ROW_H + 2).fill(hex(theme.brandTint));
    pdf
      .moveTo(MARGIN, this.y)
      .lineTo(MARGIN + this.width, this.y)
      .lineWidth(1.2)
      .strokeColor(hex(theme.brand))
      .stroke();
    pdf.font(FONT_BOLD).fontSize(8).fillColor(hex(theme.brandDark));
    let x = MARGIN;
    section.columns.forEach((col, i) => {
      let text = '';
      if (i === 0) text = 'Total';
      if (col.total) text = formatTotal(section.rows, col);
      if (text) this.cellText(text, x, this.y + 6, widths[i], alignOf(col.format));
      x += widths[i];
    });
    this.y += ROW_H + 2;
  }

  // ── Helpers ─────────────────────────────────────────────────────────

  private sectionHeading(label: string) {
    const { pdf } = this;
    pdf.font(FONT_BOLD).fontSize(12).fillColor(hex(theme.brandDark));
    this.text(label, MARGIN, this.y, { width: this.width });
    pdf
      .moveTo(MARGIN, this.y + 17)
      .lineTo(MARGIN + this.width, this.y + 17)
      .lineWidth(1)
      .strokeColor(hex(theme.brand))
      .stroke();
    this.y += 26;
  }

  private ensure(height: number) {
    if (this.y + height > this.bottom) {
      this.pdf.addPage();
      this.y = MARGIN;
    }
  }

  /**
   * Column widths (pt), sized from the measured width of the actual content.
   * Columns that already fit keep what they need; when the table is wider than
   * the page, the space is shared out so only the longest columns get clipped.
   */
  private columnWidths(section: ExportSection): number[] {
    const { pdf } = this;
    const desired = section.columns.map((col) => {
      const format = col.format ?? 'text';
      pdf.font(FONT_BOLD).fontSize(8);
      let widest = pdf.widthOfString(pdfSafe(col.header));
      pdf.font(FONT).fontSize(format === 'status' ? 7 : 8);
      for (const row of section.rows.slice(0, 200)) {
        widest = Math.max(widest, pdf.widthOfString(pdfSafe(formatValue(row[col.key], format))));
      }
      if (col.total) {
        // the totals row is wider than any single row it sums
        pdf.font(FONT_BOLD).fontSize(8);
        widest = Math.max(widest, pdf.widthOfString(pdfSafe(formatTotal(section.rows, col))));
      }
      // status text also sits inside a padded pill
      const need = widest + CELL_PAD * 2 + (format === 'status' ? 14 : 0);
      const cap = col.width ? col.width * 4.4 + CELL_PAD * 2 : 210;
      return Math.max(38, Math.min(need, cap));
    });

    const sum = desired.reduce((a, b) => a + b, 0);
    if (sum <= this.width) {
      const scale = this.width / sum; // spread the spare room evenly
      return desired.map((w) => w * scale);
    }

    const widths = new Array<number>(desired.length).fill(0);
    let pending = desired.map((_, i) => i);
    let room = this.width;
    for (;;) {
      const share = room / pending.length;
      const fits = pending.filter((i) => desired[i] <= share);
      if (fits.length === 0) break;
      for (const i of fits) {
        widths[i] = desired[i];
        room -= desired[i];
      }
      pending = pending.filter((i) => !fits.includes(i));
      if (pending.length === 0) return widths;
    }
    for (const i of pending) widths[i] = room / pending.length;
    return widths;
  }

  /** Single-line cell text, clipped with an ellipsis so it never spills. */
  private cellText(
    raw: string,
    x: number,
    y: number,
    colW: number,
    align: 'left' | 'right' | 'center',
  ) {
    const maxW = colW - CELL_PAD * 2;
    const text = this.fit(pdfSafe(raw), maxW);
    const textW = this.pdf.widthOfString(text);
    const tx =
      align === 'right'
        ? x + colW - CELL_PAD - textW
        : align === 'center'
          ? x + (colW - textW) / 2
          : x + CELL_PAD;
    this.pdf.text(text, tx, y, { lineBreak: false });
  }

  private fit(text: string, maxW: number): string {
    const { pdf } = this;
    if (pdf.widthOfString(text) <= maxW) return text;
    let end = text.length;
    while (end > 1 && pdf.widthOfString(`${text.slice(0, end)}...`) > maxW) end--;
    return `${text.slice(0, end)}...`;
  }

  /** Every draw call goes through here: sanitised, never auto-wraps/paginates. */
  private text(
    raw: string,
    x: number,
    y: number,
    opts: { width?: number; align?: 'left' | 'right' | 'center'; ellipsis?: boolean } = {},
  ) {
    const text = pdfSafe(raw);
    const fitted = opts.width && opts.ellipsis ? this.fit(text, opts.width) : text;
    this.pdf.text(fitted, x, y, { lineBreak: false, width: opts.width, align: opts.align });
  }
}

function formatTotal(rows: Record<string, unknown>[], col: ExportColumn): string {
  const sum = rows.reduce((acc, r) => acc + (toNumber(r[col.key]) ?? 0), 0);
  return formatValue(sum, col.format ?? 'number');
}

function alignOf(format?: CellFormat): 'left' | 'right' | 'center' {
  switch (format) {
    case 'integer':
    case 'number':
    case 'currency':
    case 'percent':
      return 'right';
    case 'date':
    case 'datetime':
    case 'status':
      return 'center';
    default:
      return 'left';
  }
}
